### DISCUSSION TITLE
Styling a Mermaid node in a Markdown file via CSS

### DISCUSSION THREAD

**Discussion by JosueGauthier** [mermaid-js/mermaid#4311] [Q&A]
Hello,

I would like to customize globally my Mermaid diagram in a Markdown file. 

I declare a style balise and put : green2 > rect that enable to change style of a node in Mermaid. The problem is that the caption "Node A" don't change its color. 

```

A[Node A]:::green2--> B[Node B];

```

However if i put this it works perfectly:

```
classDef green2 fill:#01ff70,stroke:#000,stroke-width:2px,color:#000
```

Here the css : 

```css
<style>

.green2 > rect {
    fill:#01ff70 !important;
    stroke:#000 !important;
    stroke-width:2px !important;
    color : rgb(173,216,230);

}

</style>
```

Thanks !
