### DISCUSSION TITLE
Can I config gantt in Markdown?

### DISCUSSION THREAD

**Discussion by tongyaop** [mermaid-js/mermaid#4823] [Q&A]
Working in VScode, ultimately the markdown will be rendered with github. 
```
:::mermaid
gantt
    title this is going to be a pretty long project
    axisFormat  %d %b
        task1          : done,   2023-09-06, 2d
        task2          : done,   2023-09-06, 2d
        task_xyzabc: active, 2023-09-11, 3d
:::
```

As other posts have mentioned the default setting for gannt is hard to read. I would like to add ganttConfiguration in my markdown file.
```
mermaid.ganttConfig = {
  titleTopMargin: 25,
  barHeight: 20,
  barGap: 4,
  topPadding: 75,
  sidePadding: 75,
};
```

**Comment by lwjohnst86** [comment]
I just learned about this too, I had no idea how to do this since it isn't well documented. But you add this to the top of the Mermaid file/diagram:

```
---
config:
    theme: "neutral"
    themeCSS: "..."
    gantt:
        barHeight: 50
        leftPadding: 15
        fontSize: 16
        sectionFontSize: 16
        barGap: 10
---
```

The config options are described here: https://mermaid.js.org/config/schema-docs/config-defs-gantt-diagram-config.html
