### ISSUE TITLE
In HTML context, neutral/null theme doesn't work; CSS injected via themeCSS doesn't take effect

### ISSUE THREAD

**Issue by benlk** [mermaid-js/mermaid#1034]
## Describe the bug
I've tried setting `theme: null` or `theme: "neutral"` to disable the pre-defined mermaid theme (https://mermaidjs.github.io/#/mermaidAPI?id=theme), and I've tried providing css for the `themeCSS` option in the config object passed to `mermaid.initialize()`.

However, the default theme is still applied, and the styles passed to `themeCSS` are not applied to the SVGs.

If I set `theme: "forest"` the forest theme is applied.

## To Reproduce
Here's the test case I'm using:

```html
<figure class="fullwidth mermaid">
graph LR
	a-->b
	subgraph test-case
		c-->d
	end
</figure>

<script src="https://cdn.jsdelivr.net/npm/mermaid@8.4.0/dist/mermaid.min.js"></script>
<script>
	window.addEventListener(
		'load',
		function() {
			var output = mermaid.initialize({
				logLevel: 0,
				startOnLoad: true,
				theme: null,
				themeCSS: document.getElementById('mermaidcss').innerText.replace(/(\r\n|\n|\r|\t)/gm, ""), // strip chars that would break CSS interpretation
				flowchart: {
					htmlLabels: true,
					curve: 'basis'
				},
				state: {
					padding: 2,
					notemargin: 5,
					fontSize: 16
				}
			});
		},
		false
	);
</script>
<style type="text/css" id="mermaidcss">
	.node rect {
		fill: white;
		stroke: hsl( 33, 98%, 68%);
	}
	.cluster rect {
		fill: transparent;
		stroke: hsl( 33, 98%, 32%);
	}
</style>
<style type="text/css">
	:root {
		--mermaid-font-family: var( --font-sans ) !important;
	}
</style>
```

## Expected behavior

I expect:

- the `.node rect` styles to be scoped to apply within the generated Mermaid classes via the `#mermaid-1572198876158` selector application
- the `.cluster rect` styles likewise

Instead, those aren't reflected in the `style` element added to the SVG. Here's its prettified contents:

<details>
<summary>Very long CSS paste</summary>

```css


#mermaid-1572198876158 .label {
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family);
	color: #333
}

#mermaid-1572198876158 .label text {
	fill: #333
}

#mermaid-1572198876158 .node rect,
#mermaid-1572198876158 .node circle,
#mermaid-1572198876158 .node ellipse,
#mermaid-1572198876158 .node polygon {
	fill: #ECECFF;
	stroke: #9370db;
	stroke-width: 1px
}

#mermaid-1572198876158 .node .label {
	text-align: center
}

#mermaid-1572198876158 .node.clickable {
	cursor: pointer
}

#mermaid-1572198876158 .arrowheadPath {
	fill: #333
}

#mermaid-1572198876158 .edgePath .path {
	stroke: #333;
	stroke-width: 1.5px
}

#mermaid-1572198876158 .edgeLabel {
	background-color: #e8e8e8;
	text-align: center
}

#mermaid-1572198876158 .cluster rect {
	fill: #ffffde;
	stroke: #aa3;
	stroke-width: 1px
}

#mermaid-1572198876158 .cluster text {
	fill: #333
}

#mermaid-1572198876158 div.mermaidTooltip {
	position: absolute;
	text-align: center;
	max-width: 200px;
	padding: 2px;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family);
	font-size: 12px;
	background: #ffffde;
	border: 1px solid #aa3;
	border-radius: 2px;
	pointer-events: none;
	z-index: 100
}

#mermaid-1572198876158 .actor {
	stroke: #ccf;
	fill: #ECECFF
}

#mermaid-1572198876158 text.actor {
	fill: #000;
	stroke: none
}

#mermaid-1572198876158 .actor-line {
	stroke: grey
}

#mermaid-1572198876158 .messageLine0 {
	stroke-width: 1.5;
	stroke-dasharray: '2 2';
	stroke: #333
}

#mermaid-1572198876158 .messageLine1 {
	stroke-width: 1.5;
	stroke-dasharray: '2 2';
	stroke: #333
}

#mermaid-1572198876158 #arrowhead {
	fill: #333
}

#mermaid-1572198876158 .sequenceNumber {
	fill: #fff
}

#mermaid-1572198876158 #sequencenumber {
	fill: #333
}

#mermaid-1572198876158 #crosshead path {
	fill: #333 !important;
	stroke: #333 !important
}

#mermaid-1572198876158 .messageText {
	fill: #333;
	stroke: none
}

#mermaid-1572198876158 .labelBox {
	stroke: #ccf;
	fill: #ECECFF
}

#mermaid-1572198876158 .labelText {
	fill: #000;
	stroke: none
}

#mermaid-1572198876158 .loopText {
	fill: #000;
	stroke: none
}

#mermaid-1572198876158 .loopLine {
	stroke-width: 2;
	stroke-dasharray: '2 2';
	stroke: #ccf
}

#mermaid-1572198876158 .note {
	stroke: #aa3;
	fill: #fff5ad
}

#mermaid-1572198876158 .noteText {
	fill: black;
	stroke: none;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family);
	font-size: 14px
}

#mermaid-1572198876158 .activation0 {
	fill: #f4f4f4;
	stroke: #666
}

#mermaid-1572198876158 .activation1 {
	fill: #f4f4f4;
	stroke: #666
}

#mermaid-1572198876158 .activation2 {
	fill: #f4f4f4;
	stroke: #666
}

#mermaid-1572198876158 .mermaid-main-font {
	font-family: "trebuchet ms", verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 .section {
	stroke: none;
	opacity: 0.2
}

#mermaid-1572198876158 .section0 {
	fill: rgba(102, 102, 255, 0.49)
}

#mermaid-1572198876158 .section2 {
	fill: #fff400
}

#mermaid-1572198876158 .section1,
#mermaid-1572198876158 .section3 {
	fill: #fff;
	opacity: 0.2
}

#mermaid-1572198876158 .sectionTitle0 {
	fill: #333
}

#mermaid-1572198876158 .sectionTitle1 {
	fill: #333
}

#mermaid-1572198876158 .sectionTitle2 {
	fill: #333
}

#mermaid-1572198876158 .sectionTitle3 {
	fill: #333
}

#mermaid-1572198876158 .sectionTitle {
	text-anchor: start;
	font-size: 11px;
	text-height: 14px;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 .grid .tick {
	stroke: #d3d3d3;
	opacity: 0.3;
	shape-rendering: crispEdges
}

#mermaid-1572198876158 .grid .tick text {
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 .grid path {
	stroke-width: 0
}

#mermaid-1572198876158 .today {
	fill: none;
	stroke: red;
	stroke-width: 2px
}

#mermaid-1572198876158 .task {
	stroke-width: 2
}

#mermaid-1572198876158 .taskText {
	text-anchor: middle;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 .taskText:not([font-size]) {
	font-size: 11px
}

#mermaid-1572198876158 .taskTextOutsideRight {
	fill: #000;
	text-anchor: start;
	font-size: 11px;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 .taskTextOutsideLeft {
	fill: #000;
	text-anchor: end;
	font-size: 11px
}

#mermaid-1572198876158 .task.clickable {
	cursor: pointer
}

#mermaid-1572198876158 .taskText.clickable {
	cursor: pointer;
	fill: #003163 !important;
	font-weight: bold
}

#mermaid-1572198876158 .taskTextOutsideLeft.clickable {
	cursor: pointer;
	fill: #003163 !important;
	font-weight: bold
}

#mermaid-1572198876158 .taskTextOutsideRight.clickable {
	cursor: pointer;
	fill: #003163 !important;
	font-weight: bold
}

#mermaid-1572198876158 .taskText0,
#mermaid-1572198876158 .taskText1,
#mermaid-1572198876158 .taskText2,
#mermaid-1572198876158 .taskText3 {
	fill: #fff
}

#mermaid-1572198876158 .task0,
#mermaid-1572198876158 .task1,
#mermaid-1572198876158 .task2,
#mermaid-1572198876158 .task3 {
	fill: #8a90dd;
	stroke: #534fbc
}

#mermaid-1572198876158 .taskTextOutside0,
#mermaid-1572198876158 .taskTextOutside2 {
	fill: #000
}

#mermaid-1572198876158 .taskTextOutside1,
#mermaid-1572198876158 .taskTextOutside3 {
	fill: #000
}

#mermaid-1572198876158 .active0,
#mermaid-1572198876158 .active1,
#mermaid-1572198876158 .active2,
#mermaid-1572198876158 .active3 {
	fill: #bfc7ff;
	stroke: #534fbc
}

#mermaid-1572198876158 .activeText0,
#mermaid-1572198876158 .activeText1,
#mermaid-1572198876158 .activeText2,
#mermaid-1572198876158 .activeText3 {
	fill: #000 !important
}

#mermaid-1572198876158 .done0,
#mermaid-1572198876158 .done1,
#mermaid-1572198876158 .done2,
#mermaid-1572198876158 .done3 {
	stroke: grey;
	fill: #d3d3d3;
	stroke-width: 2
}

#mermaid-1572198876158 .doneText0,
#mermaid-1572198876158 .doneText1,
#mermaid-1572198876158 .doneText2,
#mermaid-1572198876158 .doneText3 {
	fill: #000 !important
}

#mermaid-1572198876158 .crit0,
#mermaid-1572198876158 .crit1,
#mermaid-1572198876158 .crit2,
#mermaid-1572198876158 .crit3 {
	stroke: #f88;
	fill: red;
	stroke-width: 2
}

#mermaid-1572198876158 .activeCrit0,
#mermaid-1572198876158 .activeCrit1,
#mermaid-1572198876158 .activeCrit2,
#mermaid-1572198876158 .activeCrit3 {
	stroke: #f88;
	fill: #bfc7ff;
	stroke-width: 2
}

#mermaid-1572198876158 .doneCrit0,
#mermaid-1572198876158 .doneCrit1,
#mermaid-1572198876158 .doneCrit2,
#mermaid-1572198876158 .doneCrit3 {
	stroke: #f88;
	fill: #d3d3d3;
	stroke-width: 2;
	cursor: pointer;
	shape-rendering: crispEdges
}

#mermaid-1572198876158 .milestone {
	transform: rotate(45deg) scale(0.8, 0.8)
}

#mermaid-1572198876158 .milestoneText {
	font-style: italic
}

#mermaid-1572198876158 .doneCritText0,
#mermaid-1572198876158 .doneCritText1,
#mermaid-1572198876158 .doneCritText2,
#mermaid-1572198876158 .doneCritText3 {
	fill: #000 !important
}

#mermaid-1572198876158 .activeCritText0,
#mermaid-1572198876158 .activeCritText1,
#mermaid-1572198876158 .activeCritText2,
#mermaid-1572198876158 .activeCritText3 {
	fill: #000 !important
}

#mermaid-1572198876158 .titleText {
	text-anchor: middle;
	font-size: 18px;
	fill: #000;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 g.classGroup text {
	fill: #9370db;
	stroke: none;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family);
	font-size: 10px
}

#mermaid-1572198876158 g.classGroup text .title {
	font-weight: bolder
}

#mermaid-1572198876158 g.classGroup rect {
	fill: #ECECFF;
	stroke: #9370db
}

#mermaid-1572198876158 g.classGroup line {
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 .classLabel .box {
	stroke: none;
	stroke-width: 0;
	fill: #ECECFF;
	opacity: 0.5
}

#mermaid-1572198876158 .classLabel .label {
	fill: #9370db;
	font-size: 10px
}

#mermaid-1572198876158 .relation {
	stroke: #9370db;
	stroke-width: 1;
	fill: none
}

#mermaid-1572198876158 #compositionStart {
	fill: #9370db;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 #compositionEnd {
	fill: #9370db;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 #aggregationStart {
	fill: #ECECFF;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 #aggregationEnd {
	fill: #ECECFF;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 #dependencyStart {
	fill: #9370db;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 #dependencyEnd {
	fill: #9370db;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 #extensionStart {
	fill: #9370db;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 #extensionEnd {
	fill: #9370db;
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 .commit-id,
#mermaid-1572198876158 .commit-msg,
#mermaid-1572198876158 .branch-label {
	fill: lightgrey;
	color: lightgrey;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 .pieTitleText {
	text-anchor: middle;
	font-size: 25px;
	fill: #000;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 .slice {
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 g.stateGroup text {
	fill: #9370db;
	stroke: none;
	font-size: 10px;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

#mermaid-1572198876158 g.stateGroup text {
	fill: #9370db;
	stroke: none;
	font-size: 10px
}

#mermaid-1572198876158 g.stateGroup .state-title {
	font-weight: bolder;
	fill: #000
}

#mermaid-1572198876158 g.stateGroup rect {
	fill: #ECECFF;
	stroke: #9370db
}

#mermaid-1572198876158 g.stateGroup line {
	stroke: #9370db;
	stroke-width: 1
}

#mermaid-1572198876158 .transition {
	stroke: #9370db;
	stroke-width: 1;
	fill: none
}

#mermaid-1572198876158 .stateGroup .composit {
	fill: white;
	border-bottom: 1px
}

#mermaid-1572198876158 .state-note {
	stroke: #aa3;
	fill: #fff5ad
}

#mermaid-1572198876158 .state-note text {
	fill: black;
	stroke: none;
	font-size: 10px
}

#mermaid-1572198876158 .stateLabel .box {
	stroke: none;
	stroke-width: 0;
	fill: #ECECFF;
	opacity: 0.5
}

#mermaid-1572198876158 .stateLabel text {
	fill: #000;
	font-size: 10px;
	font-weight: bold;
	font-family: 'trebuchet ms', verdana, arial;
	font-family: var(--mermaid-font-family)
}

:root {
	--mermaid-font-family: '"trebuchet ms", verdana, arial';
	--mermaid-font-family: "Comic Sans MS", "Comic Sans", cursive
}

:root {
	--mermaid-font-family: "trebuchet ms", verdana, arial;
}
```
</details>

Note the multiple declarations of the CSS var `--mermaid-font-family`; they're why I added this style tag to my test case, to reference my stylesheet's :
```html
<style type="text/css">
	:root {
		--mermaid-font-family: var( --font-sans ) !important;
	}
</style>
```

## Screenshots

![Screen Shot 2019-10-27 at 14 00 38 ](https://user-images.githubusercontent.com/1754187/67639132-5979a900-f8c2-11e9-9034-3dfadbb85200.png)

![Screen Shot 2019-10-27 at 14 08 06 ](https://user-images.githubusercontent.com/1754187/67639193-3ef3ff80-f8c3-11e9-9ee7-7cc34a0d8316.png)

Note that the styles applied to `.node rect` from the inline stylesheet would work, except for Mermaid's theme being used. And that Mermaid's inline stylesheet doesn't contain the styles passed to `themeCSS`.

## Desktop (please complete the following information):

- Chrome 77
- Firefox 69
- Safari 13

## Additional context
This _could_ be solved by applying a more-selective selector from my CSS, except there are no IDs on any parent element of the Mermaid graph. And that would not fix the problem of theme CSS not being able to be disabled.

The CSS classes demo at https://mermaidjs.github.io/#/flowchart?id=css-classes appears to be broken as well, and might be broken in a similar way.
