### ISSUE TITLE
Flowchart arrow heads are not colored according to linkStyle settings

### ISSUE THREAD

**Issue by GDFaber** [mermaid-js/mermaid#1236]
**Describe the bug**
The arrow head color is not affected by link style `stroke` settings.

**To Reproduce**
see [live editor example](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkEgLS0-IEJcbmxpbmtTdHlsZSAwIHN0cm9rZTpyZWRcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

**Expected behavior**
Arrow heads should be colored according to link style settings as well.

**Additional context**
Tested with mermaid 8.4.6

**Comment by PickaForm** [comment]
Any news regarding the possibility to style the arrowhead properly? (at least having the same color as the stroke)

**Comment by glasgowm148** [comment]
Please change the default to grey at a minimum - black arrow head is lost on dark websites.

**Comment by dwhelan** [comment]
I believe the challenge here is that the arrowheads (markers) are actually shared by all lines that use them whereas the line is unique. So updating the color of the marker would affect all all lines using the marker.

I think this could be done by dynamically creating a unique marker when the the line is styled and applying the requested style to the new marker.

**Comment by jvsteiner** [comment]
Any update on this?

**Comment by darkoni** [comment]
I have found a workaround for styling arrow-head :-)

You can add the following CSS into your webpage:
```css
<style>
  #flowchart-pointEnd { stroke:#0f0 !important; fill:#f00 !important; stroke-width:3px !important; }
</style>
```

Notice the `!important` CSS rules.

You can define styles for other types of markers:
 #flowchart-pointEnd
 #flowchart-pointStart
 #flowchart-circleEnd
 #flowchart-circleStart
 #flowchart-crossEnd
 #flowchart-crossStart

**Comment by Nezteb** [comment]
If you want to style _all_ arrow heads to be a single color, you can do this:
```
%%{
  init: {
    'themeVariables': {
      'lineColor': '#0f0'
    }
  }
}%%

graph TD
    A --> B
```
```mermaid
%%{
  init: {
    'themeVariables': {
      'lineColor': '#0f0'
    }
  }
}%%

graph TD
    A --> B
```

Example: [playground link](https://mermaid-js.github.io/mermaid-live-editor/edit#pako:eNo9T7sKwzAM_BWjYrykkNlDoW06dmrp5EWNlcbgR3DsoYT8e10HskinO3HHLdAHTSCB80V5xow3SbIKGRNpJEcvjAbflmaxC0WyxtM12BALKw7t0IpNWv-rjJVz5ZX_RJxG9uw28cyOxxO7KA8NOIoOjS7R1VRBDVMgC9Q0YLZJQfEpr5hTeHx9DzLFTA3kSWOizmBxdyAHtPPO3rRJIe4k1fO-daxV1x9caU1H)

However, I've still not found a good way to only do it for specific arrow heads. 😅

**Comment by theory** [comment]
I was able to style the lines and arrows to match the background color and text of my blog with this CSS (all my Mermaid diagrams are in `<div class="mermaid">` elements):

```css
div.mermaid .edgeLabel {
  background-color: #151515 !important;
  color:#eaeaea !important;
}

div.mermaid .marker {
  fill: #eaeaea !important;
  stroke: #eaeaea !important;
}

div.mermaid .marker.cross {
  stroke: #eaeaea !important;
}
div.mermaid .edgePath .path {
  stroke: #eaeaea !important;
}

div.mermaid .flowchart-link {
  stroke: #eaeaea !important;
}
```

Was able to figure this out thanks to your comment, @Nezteb: I copied the style element of the diagram before and after applying your `%%{}%%` command to see what elements would need styling.
