### ISSUE TITLE
classDiagram styling does not work as documented

### ISSUE THREAD

**Issue by McShelby** [mermaid-js/mermaid#1649]
The example from the [documentation](https://mermaid-js.github.io/mermaid/#/classDiagram?id=styling) does not change color in the diagram.

```css
<style>
    .cssClass > rect{
        fill:#FF0000;
        stroke:#FFFF00;
        stroke-width:4px;
    }
</style>
```

```
classDiagram
    class Animal:::cssClass
```

This is because the current implementation puts the CSS class `cssClass` not on the SVG `g` element but directly on its `rect` subelement.

The current implementation is sub par because the divider lines between class header, variables and functions require further CSS selectors, otherwise they are not affected by styling.

I think the implementation should be changed to match the documentation.
Additionally the documentation should be changed to have a running example for styling as it is done within previous sections of the document.

 - OS: Windows
 - Browser: FF79
 - Mermaid: 8.7.0
