### ISSUE TITLE
How to change particular arrow color in sequence diagram?

### ISSUE THREAD

**Issue by hksunny10** [mermaid-js/mermaid#2687]
I'm working on sequence diagram using mermaid. But as per requirement I have to change an 2-3 arrow color not whole arrows.
How I can change this because I'm not able to find any solution on portal.

Thanks

**Comment by ashemedai** [comment]
You currently cannot do this with Mermaid, as far as I understand.

Since the arrows are SVG definitions, you need to change the SVG definition of the message lines. The message line classes, however, seem to be based on the participants. E.g. class `messageLine0` seems to be all lines going from left to right (or initiator to participant?) and class `messageLine1` seems to be all lines from right to left (or participant back to initiator?).

You can [colour](https://codepen.io/sosuke/pen/Pjoqqp) the lines with something like the following, but keep in mind there's no fine-grained control for individual lines that I can see.

```css
.mermaid .messageLine0
{
    filter: invert(51%) sepia(84%) saturate(405%) hue-rotate(21deg) brightness(94%) contrast(91%);
}
```

This will result in something like this:
![image](https://user-images.githubusercontent.com/610865/167822021-d5d0df72-6b76-4527-8761-1b6688936611.png)
