### ISSUE TITLE
Would a 'stack diagram' be of interest?

### ISSUE THREAD

**Issue by cmorganBE** [mermaid-js/mermaid#3307]
I often have a need to create stack diagrams, example below.

Would there be any interest in accepting a pull request that creates these kinds of diagrams? I think it wouldn't be too bad to capture the technique I use to create them and implement it in code, but wanted to confirm interest before starting on the effort.

![image](https://user-images.githubusercontent.com/51970032/183643114-cf5f1eff-3efb-49f1-bae5-7400ed377c98.png)

**Comment by knsv** [comment]
Yes it would! 👍

**Comment by ileixe** [comment]
Definitely :+1:

**Comment by cmorganBE** [comment]
I'll have some time off around the holidays and will dig in then, so if someone has the work planned before then please reach out (chmorgan@gmail.com), or give me until end of year :-)

**Comment by brian-methodical** [comment]
I would find this useful.

**Comment by eliaskanelis** [comment]
Is this implemented and merged? It is very useful for my needs.

**Comment by cmorganBE** [comment]
@eliaskanelis wow, august 2022, time flies... I'd like to take a crack at this during the next break I have, likely during a holiday but I'd also gladly use it if someone else puts it together earlier :-)

**Comment by eliaskanelis** [comment]
My expertise is C and C++ as I am an embedded engineer. I know some JavaScript, but at a hobby level. I have some spare time to help, but I am limited to my lack of expertise on web development. Could I help somehow?

**Comment by sidharthv96** [comment]
The first step would be to decide on a syntax that we can use. 
@knsv is this similar to the block diagram that you are working on?

**Comment by eliaskanelis** [comment]
I have done some brainstorming with a few people from work and we came to this draft:
```yml
stack:
  style: {fill: black,4pt,...}
  layer:
    block:
      style: {fill: black,4pt,...} # Inherited if not assigned from parent
      [App1]->[RTOS]
    block:
      [App2]->[RTOS]
    block:
      ["Bare metal app"]->[RTOS, Microcontroller]
  Layer:
    block:
      [RTOS]->[HAL]
  Layer:
    block:
      [HAL]->[SPI, I2C, UART, Microcontroller]
  Layer:
    block:
      [SPI]->[Microcontroller]
    block:
      [I2C]->[Microcontroller]
    block:
      [UART]->[Microcontroller]
  Layer:
    block:
      [Microcontroller]
```
That tries to describe the following.

![stack drawio](https://github.com/mermaid-js/mermaid/assets/6795214/5fef3319-8aff-4011-8770-a0c839b7869f)

I hope this helps.
