### ISSUE TITLE
Diagram Proposal: Team Topologies

### ISSUE THREAD

**Issue by Incognito** [mermaid-js/mermaid#4659]
### Proposal

Introduce a diagram type named "Team Topology" which follows the conventions from https://teamtopologies.com/ .

The syntax must be able to:
1. Identify a team name (optionally)
2. Identify one of four a team types
3. Identify which of the 3 interaction modes connects to two teams (and in the case of XaaS, what direction).
4. Identify groups of teams (if there are any) which behave like teams themselves and can have interactions.

By default: Add a "Flow of change" arrow to the top or bottom of the diagram.

Here are the core components of the diagram
![Team Topologies by Brian Graham - Team Interaction Modes](https://github.com/mermaid-js/mermaid/assets/379322/e04f196d-28f6-43f4-88fb-306c5c2f8b81)
![Team Topologies by Brian Graham - Fundamental Team Types](https://github.com/mermaid-js/mermaid/assets/379322/6eb663cb-11ec-4bc7-b24b-19fdef293900)

### Use Cases

Team Topologies is a way to diagram teams and how they interact. It is growing rapidly in popularity for software teams but also non-software companies use it.

Companies use it to discuss org structure and modelling to help teams reach "Fast Flow" of change.

### Screenshots

Here are several examples I've taken off of google image search:

![image](https://github.com/mermaid-js/mermaid/assets/379322/a0b4d667-7a05-4a20-bfc8-6a690d7e6c80)
![image](https://github.com/mermaid-js/mermaid/assets/379322/eaa8fa2a-587e-4c33-9640-738de988abef)
![image](https://github.com/mermaid-js/mermaid/assets/379322/9ed59502-ce96-4235-bf74-f9e1c18de1ea)
![image](https://github.com/mermaid-js/mermaid/assets/379322/54ed9143-4030-4ad8-92a7-eeab0b79af08)

### Syntax

There are two possibilities I can think of, and I welcome a healthy debate from anyone experienced with creating diagram syntax to pick the right one.

1. Similar to a sequence diagram or DOT notation
2. Similar yaml with nesting context

# Option 1, dot-like

From a grammatical view:

Identify a team: `[team_by_name]@[team_type]`
Identify relationships: `[group_or_team_by_name]@[team_type]-[interaction_mode]->[group_or_team_by_name]@[team_type]`
Identify that a team is nested inside a group: `[group_name]@[team_type]([team_by_name]@[team_type], [team_by_name]@[team_type])`

If team types are already defined before used in a relationship or grouping, they are optional syntax which allows a definition like this:
`[group_or_team_by_name]-[interaction_mode]->[group_or_team_by_name]`

In practice it could look like this
```
Compliance@SubSystem
ACH@Stream

Compliance--XaaS->Banking@Platform
ACH--collaboration->Banking
DevOps--Facilitation->Banking

BigOrg@Stream(Ach, Compliance)
```

# Option 2, yaml-like

```
Teams:
  - name: BigOrg # Implied as a group by being referenced later on
    type: Stream
  - name: Compliance
    type: SubSystem
    interacts: 
      XaaS: [Banking]
      collaboration: [] # Empty values are optional
      facilitation: []
    group: BigOrg # Group keys are optional, missing means there is no group
  - name: Ach
    type: Stream
    interacts: 
      collaboration: [Banking]
    group: BigOrg
  - name: DevOps
    type: Facilitation
    interacts: 
      facilitation: [Banking]
  - name: Banking
    type: Platform
```

### Implementation

I will try and implement it myself.
