### ISSUE TITLE
Add different crossing styles

### ISSUE THREAD

**Issue by iainhallam** [mermaid-js/mermaid#5181]
### Description

#334 was closed by a bot, but it's a key feature for serious diagramming work. Lines that cross should be able to be visually indicated, ideally in a user-selected choice of things like little arcs, or a break in the rear-most line.

### Steps to reproduce

Create any diagram with crossing lines. See the slightly misleading crosses.

### Setup

- Mermaid version: Current Mermaid Live as of 2024-01-05
- Browser and Version: Vivaldi 6.5.3206.39 on Windows

### Suggested Solutions

A config option for the diagram on how to show crossing lines.

**Comment by nnmrts** [comment]
Sorry for derailing this a bit, but for anyone looking for a quick workaround, you can style edges with `filter: drop-shadow(...)` to symbolize very basic line crossings, like so:

```css
.flowchart-link {
	filter:
		drop-shadow(0px 2px 0px black)
		drop-shadow(2px 0px 0px black)
		drop-shadow(0px -2px 0px black)
		drop-shadow(-2px 0px 0px black)
}
```

![Bildschirmfoto 2024-03-25 um 21 15 28](https://github.com/mermaid-js/mermaid/assets/20396367/810356e7-fb50-45e2-9804-5cc743d98389)

The color of the shadow of course needs to be the same as the background, which in this case is black.

But note that is a very bad workaround, adding css filters to a graph with already like 15 edges (at least for me) hurts performance when the graph gets animated for example. It's just not a good idea in general but the best "easy" fix I could come up for now. And if you need more space between the lines at the crossings, you have to add even more shadows, like so for 4 pixels for example:

```css
.flowchart-link {
	filter:
		drop-shadow(0px 2px 0px black)
		drop-shadow(2px 0px 0px black)
		drop-shadow(0px -2px 0px black)
		drop-shadow(-2px 0px 0px black)
		drop-shadow(0px 4px 0px black)
		drop-shadow(4px 0px 0px black)
		drop-shadow(0px -4px 0px black)
		drop-shadow(-4px 0px 0px black)
}
```

![Bildschirmfoto 2024-03-25 um 21 23 00](https://github.com/mermaid-js/mermaid/assets/20396367/954a9db3-3aa0-44d5-a0ba-7a33242007f6)

But making it thicker obviously leads to problems like these:

![Bildschirmfoto 2024-03-25 um 21 23 47](https://github.com/mermaid-js/mermaid/assets/20396367/4ea4d02f-edc3-4872-a77f-6680b591084f)

And obviously this approach is utterly useless for graphs on backgrounds that are anything but a solid color.

Because this is not a long-term solution, I'm currently working on a way to detect line crossings from the output SVG and then changing those paths to get "actual" crossings - should be possible, technically...
