### ISSUE TITLE
Control brackets around loopText and friends

### ISSUE THREAD

**Issue by Pomax** [mermaid-js/mermaid#5364]
### Proposal

Mermaid should offer a way to control whether or not it adds brackets to loopText and friends, as having control over CSS means those can be CSS `::before` and `::after` content that people can overwrite if they don't want them.

### Example

```
sequenceDiagram
    Alice->>Bob: Hello Bob, how are you?
    alt is sick
        Bob->>Alice: Not so good :(
    else is well
        Bob->>Alice: Feeling fresh like a daisy
    end
    opt Extra response
        Bob->>Alice: Thanks for asking
    end
```
With a custom style that matches whatever the user's style guide wants:

```css
.loopText {
  font-family: Helvetica;
  font-weight: bold !important;
  font-style: italic;
  fill: #4945ce !important;
  /* taking advantage of CSS in 2024 finally having nesting*/
  &:before, &:after { content: ""; }
}
```

### Screenshots

![image](https://github.com/mermaid-js/mermaid/assets/177243/2291c65f-2bdd-4003-a50a-f4bbee6ab252)
