### ISSUE TITLE
UPN - Universal Process Notation

### ISSUE THREAD

**Issue by mantielero** [mermaid-js/mermaid#5511]
### Proposal

1. It is a very simple way to describe processes.
2. I think it could be pretty similar to existing diagrams with some tailoring.
3.  There are not many alternatives to do this kind of diagrams. All of them paid options and not convenient.

There aren't many alternatives to describe processes. BPMN is one way to do it. But it is a huge specification. On the other hand, UPN is very simple.

I raised a similar proposal here: https://github.com/terrastruct/d2/issues/1702

### Use Cases

Easy way to describe processes.

### Screenshots

![](https://camo.githubusercontent.com/8bb9ee3958a7c272a01c6b26e8b65ac79dfe4eb890d6dc66ff404b14003d4cde/68747470733a2f2f656c656d656e74732e636c6f75642f6170702f75706c6f6164732f323032322f30382f31776f424d505f7973465a464670715a4b646e576a4d772e706e67)

### Syntax

For example something like:
```
process: [myProcess, Title for the process]
  - step:
    - ref: reqSupport
    - title: Request Support
    - by:
      - Customer
  
  - step:
    - ref:  resolveRequest
    - title: Resolve sales support request
    - by:
      - Sales
    - attachments:
      - [filename.pdf](files/filename.pdf)

  - step:
    - ref:  testIssue
    - title: Test Issue
    - by:
      - Test Team
    - link: detailedProcess
        
  - conn:
    - [reqSupport, resolveRequest]
    - Sales Issue


process: [detailedProcess, This is the detailed process for above's step]
....
```

### Implementation

This is a proposal which I'd love to see built into mermaid by the wonderful community.
