### ISSUE TITLE
Document declaration type of html inexpectedly changed while running js code

### ISSUE THREAD

**Issue by onford** [mermaid-js/mermaid#6469]
### Description

When I use the meriand2 plugin in [this repo](https://github.com/fralau/mkdocs-mermaid2-plugin) to generate my own mkdocs site, it occurs that the KaTeX formulars cannot render properly in the same page of meriand figures.

### Steps to reproduce

1. Add necessary configurations to `mkdocs.yaml`, as is shown below:
    ```yaml
    markdown_extensions:
      - pymdownx.superfences:
        # make exceptions to highlighting of code:
          custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
    plugins:
      - search
      - mermaid2:
          version: '9.4.3' # only works with version < 10
          arguments:
            theme: 'dark'
            themeVariables:
              primaryColor: '#BB2528'
              primaryTextColor: '#fff'
              primaryBorderColor: '#7C0000'
              lineColor: '#F8B229'
              secondaryColor: '#006100'
              tertiaryColor: '#fff'
    ```
2. Create a markdown file like this:
    ````markdown
    ```mermaid
    graph LR
        hello --> world
        world --> again
        again --> hello
    ```
    
    $E = mc^2$
    ````
3. Add this markdown file to `mkdocs.yaml`, and lauch the service of mkdocs.
4. Then we see the KaTeX formular not rendered properly.

![Image](https://github.com/user-attachments/assets/77adbbcc-a018-40f2-84ed-0b817cf934c2)

5. Also, the document type changes:

![Image](https://github.com/user-attachments/assets/129537c0-c1d7-48a0-8add-2d830713417a)
6. And take a look at the console, there are a lot of errors:

![Image](https://github.com/user-attachments/assets/0471af58-f39b-4c6e-b5a0-11f327402606)

### Code Sample

```text

```

### Setup

- Mermaid version: 9.4.3
- Browser and Version: [Edge]

### Suggested Solutions

 As is shown in [this issue](https://github.com/fralau/mkdocs-mermaid2-plugin/issues/116), we reach several conclusions:

- The KaTeX javascript code cannot run in quirks mode. That is, the declaration type of html file should be `<!DOCTYPE html>`  to ensure that KaTeX js code works. 
- The mkdocs-mermaid2-plugin does change the declaration type of html file. When adding this plugin to config, it is `<!DOCTYPE doctype>`, and it is `<!DOCTYPE html>` when not added.
- The problem may be the js code that the mkdocs-mermaid2-plugin uses. Compared with other plugins, we finally located the problem at [https://unpkg.com/mermaid@9.4.3/dist/mermaid.min.js](https://unpkg.com/mermaid@9.4.3/dist/mermaid.min.js) that the plugin uses.

I'm not sure if it's really because of the js code, but I think it of great possibility. I sincerely hope you could handle with this issue!
