### ISSUE TITLE
Accept CSS variables for theme

### ISSUE THREAD

**Issue by tuyen-at-work** [mermaid-js/mermaid#6677]
### Proposal

Please consider adding support for using CSS variables in themes.

**Example:**

Mermaid:

```yaml
config:
  themeVariables:
    git1: var(--danger)
```

CSS:

```css
:root {
  --danger: red;
}

[data-theme='dark'] {
  --danger: orange;
}
```

**Use case:**

For sites that already support multiple themes (such as light/dark modes) through a system of CSS variables, allowing Mermaid to reference these variables would significantly improve visual consistency between Mermaid diagrams and the rest of the site. It would also enable diagrams to automatically adapt when the user switches themes — something that is not currently customizable.

### Colors

Support CSS variables for all colors.
